### ISSUE TITLE
Question about the extrinsic between different sensors

### ISSUE THREAD

**Issue by Gatsby23** [ZorAttC/COLOR_SHINE_MAPPING#1]
Respected researcher,
Thank you for your work. However, I have a few questions regarding some points that are not entirely clear to me. How do you handle the relationship between the extrinsics of different sensors? It seems that your work uses the SHINE-Mapping algorithm to train the SDF based on the LiDAR sensor, and then uses a color camera for texture learning. But it appears that you didn't perform the extrinsic transformation between the LiDAR and the camera? Another question is that the output of r3live seems to be the IMU pose, and it seems you didn't perform a transformation to use it directly for SDF learning. Is my understanding correct? Thank you once again for your work.
Yours
Qi Wu

**Comment by ZorAttC** [comment]
1. The extrinsic transformation of LiDAR nad camera actually is calibrated in R3live,I just use the colored result.
2. ![image](https://github.com/ZorAttC/COLOR_SHINE_MAPPING/assets/93999826/a2e5ee6f-ba6e-45bf-a2b6-492ecec746a4)
As you can see from the code from r3live,I think that the transformation from LiDAR to Imu has no rotation.Note the transformation from Imu to Lidar as T|IL(rotation is identity, only translation exists),the transformation from Imu to world as T|WI,the global point coordinate will be T|WI * T|IL *p. There will be a shift related to the pose rotation,and I think it doesn't affect the performance it just shifts.
But it ain't right anyway,so you can just fixe it by add the offset.

Hope it can help you.

**Comment by Gatsby23** [comment]
> 1. The extrinsic transformation of LiDAR nad camera actually is calibrated in R3live,I just use the colored result.
> 2. ![image](https://private-user-images.githubusercontent.com/93999826/341652511-a2e5ee6f-ba6e-45bf-a2b6-492ecec746a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NTA0MDMsIm5iZiI6MTcxODk1MDEwMywicGF0aCI6Ii85Mzk5OTgyNi8zNDE2NTI1MTEtYTJlNWVlNmYtYmE2ZS00NWJmLWEyYjYtNDkyZWNlYzc0NmE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDA2MDgyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjMDFlNmYzZjk4ZDU5NzFhN2E4MGVmNTg3NTYzMDUzZjNlNDMzNWUzZTYxNWUwNDRmNzYyYWExZjdmNGM2NGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QPiB1Omi9HC0OV_ZZAa5ulT2iRbJKBPosiymycNPvyA)
>    As you can see from the code from r3live,I think that the transformation from LiDAR to Imu has no rotation.Note the transformation from Imu to Lidar as T|IL(rotation is identity, only translation exists),the transformation from Imu to world as T|WI,the global point coordinate will be T|WI * T|IL *p. There will be a shift related to the pose rotation,and I think it doesn't affect the performance it just shifts.
>    But it ain't right anyway,so you can just fixe it by add the offset.
> 
> Hope it can help you.

I get your point! Nice idea.
